name: Pantelis Roditis
description: "the rumblings of a unix geekopath #blame-🤬databus"
avatar: https://proditis.github.io/images/blacksheep-avatar.png
footer-links:
  discord: https://discord.gg/usGhmRzCqB
  github: proditis
  linkedin: pantelis-roditis-07504634
  rss: RSS
  twitter: PantelisRoditis
#google_analytics:
url: https://proditis.github.io
baseurl: ""
permalink: /:categories/:title/
show_downloads: false
github:
  is_project_page: false
defaults:
  - scope:
      path: ""
    values:
      image: /images/blacksheep-social.png

collections:
  research:
    output: true
  thoughts:
    output: true

version: v1.2.0
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

sass:
  style: :expanded # You might prefer to minify using :compressed

safe: true
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-toc

whitelist:
  - jekyll-toc

toc:
 min_level: 1
 max_level: 3
 list_class: toc
 list_class: toc__list
 sublist_class: toc__sublist

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
