name: Pantelis Roditis
description: \#blame-🤬databus
avatar: https://proditis.github.io/images/blacksheep-avatar.png
footer-links:
  discord: https://discord.gg/usGhmRzCqB
  github: proditis
  linkedin: pantelis-roditis-07504634
  rss: RSS
  twitter: PantelisRoditis
#google_analytics:
url: https://proditis.github.io
baseurl: ""
permalink: /:title/
version: v1.2.0
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

sass:
  style: :expanded # You might prefer to minify using :compressed

gems:
  - jekyll-sitemap
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
